
-- Creamos la base de datos de la distribuidora

DROP SCHEMA IF EXISTS Distribuidora;

CREATE SCHEMA IF NOT EXISTS Distribuidora;

USE Distribuidora;

-- Creamos las tablas

DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
	ID_Cliente INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    CL_Nombre VARCHAR(25) NOT NULL,
    CL_Apellido VARCHAR(25) NOT NULL,
    CL_DNI INT NOT NULL UNIQUE,
    CL_CUIT VARCHAR(13) NOT NULL UNIQUE,
    CL_TELEFONO INT NOT NULL,
    CL_Email VARCHAR(50)
);

DROP TABLE IF EXISTS direccion_clientes;

CREATE TABLE direccion_clientes (
	ID_DireccionCliente INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    CL_Direccion VARCHAR(50) NOT NULL,
    CL_CodigoPostal INT NOT NULL,
    CL_Zona VARCHAR(25) NOT NULL,
    ID_Cliente INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_Cliente) REFERENCES clientes(ID_Cliente) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS productos;

CREATE TABLE productos (
	ID_Producto INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Producto VARCHAR(15) NOT NULL,
    Marca VARCHAR(25) NOT NULL,
    Modelo VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS detalle_productos;

CREATE TABLE detalle_productos (
	ID_DetalleProducto INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    ID_Producto INT NOT NULL UNIQUE,
    PT_Costo NUMERIC(10,2) NOT NULL,
    PT_Precio NUMERIC(10,2) NOT NULL,
    PT_Stock INT NOT NULL,
    PT_Codigo INT NOT NULL,
    FOREIGN KEY (ID_Producto) REFERENCES productos(ID_Producto) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS empleados;

CREATE TABLE empleados (
	ID_Empleado INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    EP_Nombre VARCHAR(25) NOT NULL,
    EP_Apellido VARCHAR(25) NOT NULL,
    EP_DNI INT NOT NULL UNIQUE,
    EP_Telefono INT NOT NULL
);

DROP TABLE IF EXISTS area_empleados;

CREATE TABLE area_empleados (
	ID_AreaAsignada INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    EP_Area VARCHAR(25) NOT NULL,
    ID_Empleado INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_Empleado) REFERENCES empleados(ID_Empleado) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS pedidos;

CREATE TABLE pedidos (
	ID_Pedido INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    PD_Fecha DATE NOT NULL,
	PD_Monto NUMERIC(10,2) NOT NULL,
    ID_Cliente INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_Cliente) REFERENCES clientes(ID_Cliente) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS facturas;

CREATE TABLE facturas (
	ID_Factura INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    FC_Fecha DATE NOT NULL,
	FC_Monto NUMERIC(10,2) NOT NULL,
    ID_Cliente INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_Cliente) REFERENCES clientes(ID_Cliente) ON DELETE CASCADE ON UPDATE CASCADE
);




